//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RttClient.ClientService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientDetail", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClientDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        private long IdNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((this.IdNumberField.Equals(value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AddressDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        private System.Guid ClientIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StreetAddressLine1 {
            get {
                return this.StreetAddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressLine1Field, value) != true)) {
                    this.StreetAddressLine1Field = value;
                    this.RaisePropertyChanged("StreetAddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StreetAddressLine2 {
            get {
                return this.StreetAddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressLine2Field, value) != true)) {
                    this.StreetAddressLine2Field = value;
                    this.RaisePropertyChanged("StreetAddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Guid ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ContactDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientService.DataServiceSoap")]
    public interface DataServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllClientsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClients", ReplyAction="*")]
        RttClient.ClientService.GetAllClientsResponse GetAllClients(RttClient.ClientService.GetAllClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllClients", ReplyAction="*")]
        System.Threading.Tasks.Task<RttClient.ClientService.GetAllClientsResponse> GetAllClientsAsync(RttClient.ClientService.GetAllClientsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveClientData", ReplyAction="*")]
        RttClient.ClientService.SaveClientDataResponse SaveClientData(RttClient.ClientService.SaveClientDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveClientData", ReplyAction="*")]
        System.Threading.Tasks.Task<RttClient.ClientService.SaveClientDataResponse> SaveClientDataAsync(RttClient.ClientService.SaveClientDataRequest request);
        
        // CODEGEN: Generating message contract since element name streetAddressline1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAddressData", ReplyAction="*")]
        RttClient.ClientService.SaveAddressDataResponse SaveAddressData(RttClient.ClientService.SaveAddressDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAddressData", ReplyAction="*")]
        System.Threading.Tasks.Task<RttClient.ClientService.SaveAddressDataResponse> SaveAddressDataAsync(RttClient.ClientService.SaveAddressDataRequest request);
        
        // CODEGEN: Generating message contract since element name clientId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveContactData", ReplyAction="*")]
        RttClient.ClientService.SaveContactDataResponse SaveContactData(RttClient.ClientService.SaveContactDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveContactData", ReplyAction="*")]
        System.Threading.Tasks.Task<RttClient.ClientService.SaveContactDataResponse> SaveContactDataAsync(RttClient.ClientService.SaveContactDataRequest request);
        
        // CODEGEN: Generating message contract since element name clientId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddressDetails", ReplyAction="*")]
        RttClient.ClientService.GetAddressDetailsResponse GetAddressDetails(RttClient.ClientService.GetAddressDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddressDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<RttClient.ClientService.GetAddressDetailsResponse> GetAddressDetailsAsync(RttClient.ClientService.GetAddressDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name clientId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactDetails", ReplyAction="*")]
        RttClient.ClientService.GetContactDetailsResponse GetContactDetails(RttClient.ClientService.GetContactDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<RttClient.ClientService.GetContactDetailsResponse> GetContactDetailsAsync(RttClient.ClientService.GetContactDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllClientsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllClients", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.GetAllClientsRequestBody Body;
        
        public GetAllClientsRequest() {
        }
        
        public GetAllClientsRequest(RttClient.ClientService.GetAllClientsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllClientsRequestBody {
        
        public GetAllClientsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllClientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllClientsResponse", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.GetAllClientsResponseBody Body;
        
        public GetAllClientsResponse() {
        }
        
        public GetAllClientsResponse(RttClient.ClientService.GetAllClientsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllClientsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RttClient.ClientService.ClientDetail[] GetAllClientsResult;
        
        public GetAllClientsResponseBody() {
        }
        
        public GetAllClientsResponseBody(RttClient.ClientService.ClientDetail[] GetAllClientsResult) {
            this.GetAllClientsResult = GetAllClientsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveClientDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveClientData", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.SaveClientDataRequestBody Body;
        
        public SaveClientDataRequest() {
        }
        
        public SaveClientDataRequest(RttClient.ClientService.SaveClientDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveClientDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long idNumber;
        
        public SaveClientDataRequestBody() {
        }
        
        public SaveClientDataRequestBody(string name, string surname, string gender, long idNumber) {
            this.name = name;
            this.surname = surname;
            this.gender = gender;
            this.idNumber = idNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveClientDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveClientDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.SaveClientDataResponseBody Body;
        
        public SaveClientDataResponse() {
        }
        
        public SaveClientDataResponse(RttClient.ClientService.SaveClientDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveClientDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveClientDataResult;
        
        public SaveClientDataResponseBody() {
        }
        
        public SaveClientDataResponseBody(bool SaveClientDataResult) {
            this.SaveClientDataResult = SaveClientDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveAddressDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveAddressData", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.SaveAddressDataRequestBody Body;
        
        public SaveAddressDataRequest() {
        }
        
        public SaveAddressDataRequest(RttClient.ClientService.SaveAddressDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveAddressDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string streetAddressline1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string streetAddressline2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string province;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string postalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string clientId;
        
        public SaveAddressDataRequestBody() {
        }
        
        public SaveAddressDataRequestBody(string streetAddressline1, string streetAddressline2, string city, string province, string postalCode, string clientId) {
            this.streetAddressline1 = streetAddressline1;
            this.streetAddressline2 = streetAddressline2;
            this.city = city;
            this.province = province;
            this.postalCode = postalCode;
            this.clientId = clientId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveAddressDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveAddressDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.SaveAddressDataResponseBody Body;
        
        public SaveAddressDataResponse() {
        }
        
        public SaveAddressDataResponse(RttClient.ClientService.SaveAddressDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveAddressDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveAddressDataResult;
        
        public SaveAddressDataResponseBody() {
        }
        
        public SaveAddressDataResponseBody(bool SaveAddressDataResult) {
            this.SaveAddressDataResult = SaveAddressDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveContactDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveContactData", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.SaveContactDataRequestBody Body;
        
        public SaveContactDataRequest() {
        }
        
        public SaveContactDataRequest(RttClient.ClientService.SaveContactDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveContactDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string number;
        
        public SaveContactDataRequestBody() {
        }
        
        public SaveContactDataRequestBody(string clientId, string Type, string number) {
            this.clientId = clientId;
            this.Type = Type;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveContactDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveContactDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.SaveContactDataResponseBody Body;
        
        public SaveContactDataResponse() {
        }
        
        public SaveContactDataResponse(RttClient.ClientService.SaveContactDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveContactDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveContactDataResult;
        
        public SaveContactDataResponseBody() {
        }
        
        public SaveContactDataResponseBody(bool SaveContactDataResult) {
            this.SaveContactDataResult = SaveContactDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddressDetails", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.GetAddressDetailsRequestBody Body;
        
        public GetAddressDetailsRequest() {
        }
        
        public GetAddressDetailsRequest(RttClient.ClientService.GetAddressDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAddressDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientId;
        
        public GetAddressDetailsRequestBody() {
        }
        
        public GetAddressDetailsRequestBody(string clientId) {
            this.clientId = clientId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddressDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.GetAddressDetailsResponseBody Body;
        
        public GetAddressDetailsResponse() {
        }
        
        public GetAddressDetailsResponse(RttClient.ClientService.GetAddressDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAddressDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RttClient.ClientService.AddressDetails[] GetAddressDetailsResult;
        
        public GetAddressDetailsResponseBody() {
        }
        
        public GetAddressDetailsResponseBody(RttClient.ClientService.AddressDetails[] GetAddressDetailsResult) {
            this.GetAddressDetailsResult = GetAddressDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactDetails", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.GetContactDetailsRequestBody Body;
        
        public GetContactDetailsRequest() {
        }
        
        public GetContactDetailsRequest(RttClient.ClientService.GetContactDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContactDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientId;
        
        public GetContactDetailsRequestBody() {
        }
        
        public GetContactDetailsRequestBody(string clientId) {
            this.clientId = clientId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public RttClient.ClientService.GetContactDetailsResponseBody Body;
        
        public GetContactDetailsResponse() {
        }
        
        public GetContactDetailsResponse(RttClient.ClientService.GetContactDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContactDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RttClient.ClientService.ContactDetails[] GetContactDetailsResult;
        
        public GetContactDetailsResponseBody() {
        }
        
        public GetContactDetailsResponseBody(RttClient.ClientService.ContactDetails[] GetContactDetailsResult) {
            this.GetContactDetailsResult = GetContactDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : RttClient.ClientService.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<RttClient.ClientService.DataServiceSoap>, RttClient.ClientService.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RttClient.ClientService.GetAllClientsResponse RttClient.ClientService.DataServiceSoap.GetAllClients(RttClient.ClientService.GetAllClientsRequest request) {
            return base.Channel.GetAllClients(request);
        }
        
        public RttClient.ClientService.ClientDetail[] GetAllClients() {
            RttClient.ClientService.GetAllClientsRequest inValue = new RttClient.ClientService.GetAllClientsRequest();
            inValue.Body = new RttClient.ClientService.GetAllClientsRequestBody();
            RttClient.ClientService.GetAllClientsResponse retVal = ((RttClient.ClientService.DataServiceSoap)(this)).GetAllClients(inValue);
            return retVal.Body.GetAllClientsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RttClient.ClientService.GetAllClientsResponse> RttClient.ClientService.DataServiceSoap.GetAllClientsAsync(RttClient.ClientService.GetAllClientsRequest request) {
            return base.Channel.GetAllClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RttClient.ClientService.GetAllClientsResponse> GetAllClientsAsync() {
            RttClient.ClientService.GetAllClientsRequest inValue = new RttClient.ClientService.GetAllClientsRequest();
            inValue.Body = new RttClient.ClientService.GetAllClientsRequestBody();
            return ((RttClient.ClientService.DataServiceSoap)(this)).GetAllClientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RttClient.ClientService.SaveClientDataResponse RttClient.ClientService.DataServiceSoap.SaveClientData(RttClient.ClientService.SaveClientDataRequest request) {
            return base.Channel.SaveClientData(request);
        }
        
        public bool SaveClientData(string name, string surname, string gender, long idNumber) {
            RttClient.ClientService.SaveClientDataRequest inValue = new RttClient.ClientService.SaveClientDataRequest();
            inValue.Body = new RttClient.ClientService.SaveClientDataRequestBody();
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.gender = gender;
            inValue.Body.idNumber = idNumber;
            RttClient.ClientService.SaveClientDataResponse retVal = ((RttClient.ClientService.DataServiceSoap)(this)).SaveClientData(inValue);
            return retVal.Body.SaveClientDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RttClient.ClientService.SaveClientDataResponse> RttClient.ClientService.DataServiceSoap.SaveClientDataAsync(RttClient.ClientService.SaveClientDataRequest request) {
            return base.Channel.SaveClientDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<RttClient.ClientService.SaveClientDataResponse> SaveClientDataAsync(string name, string surname, string gender, long idNumber) {
            RttClient.ClientService.SaveClientDataRequest inValue = new RttClient.ClientService.SaveClientDataRequest();
            inValue.Body = new RttClient.ClientService.SaveClientDataRequestBody();
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.gender = gender;
            inValue.Body.idNumber = idNumber;
            return ((RttClient.ClientService.DataServiceSoap)(this)).SaveClientDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RttClient.ClientService.SaveAddressDataResponse RttClient.ClientService.DataServiceSoap.SaveAddressData(RttClient.ClientService.SaveAddressDataRequest request) {
            return base.Channel.SaveAddressData(request);
        }
        
        public bool SaveAddressData(string streetAddressline1, string streetAddressline2, string city, string province, string postalCode, string clientId) {
            RttClient.ClientService.SaveAddressDataRequest inValue = new RttClient.ClientService.SaveAddressDataRequest();
            inValue.Body = new RttClient.ClientService.SaveAddressDataRequestBody();
            inValue.Body.streetAddressline1 = streetAddressline1;
            inValue.Body.streetAddressline2 = streetAddressline2;
            inValue.Body.city = city;
            inValue.Body.province = province;
            inValue.Body.postalCode = postalCode;
            inValue.Body.clientId = clientId;
            RttClient.ClientService.SaveAddressDataResponse retVal = ((RttClient.ClientService.DataServiceSoap)(this)).SaveAddressData(inValue);
            return retVal.Body.SaveAddressDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RttClient.ClientService.SaveAddressDataResponse> RttClient.ClientService.DataServiceSoap.SaveAddressDataAsync(RttClient.ClientService.SaveAddressDataRequest request) {
            return base.Channel.SaveAddressDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<RttClient.ClientService.SaveAddressDataResponse> SaveAddressDataAsync(string streetAddressline1, string streetAddressline2, string city, string province, string postalCode, string clientId) {
            RttClient.ClientService.SaveAddressDataRequest inValue = new RttClient.ClientService.SaveAddressDataRequest();
            inValue.Body = new RttClient.ClientService.SaveAddressDataRequestBody();
            inValue.Body.streetAddressline1 = streetAddressline1;
            inValue.Body.streetAddressline2 = streetAddressline2;
            inValue.Body.city = city;
            inValue.Body.province = province;
            inValue.Body.postalCode = postalCode;
            inValue.Body.clientId = clientId;
            return ((RttClient.ClientService.DataServiceSoap)(this)).SaveAddressDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RttClient.ClientService.SaveContactDataResponse RttClient.ClientService.DataServiceSoap.SaveContactData(RttClient.ClientService.SaveContactDataRequest request) {
            return base.Channel.SaveContactData(request);
        }
        
        public bool SaveContactData(string clientId, string Type, string number) {
            RttClient.ClientService.SaveContactDataRequest inValue = new RttClient.ClientService.SaveContactDataRequest();
            inValue.Body = new RttClient.ClientService.SaveContactDataRequestBody();
            inValue.Body.clientId = clientId;
            inValue.Body.Type = Type;
            inValue.Body.number = number;
            RttClient.ClientService.SaveContactDataResponse retVal = ((RttClient.ClientService.DataServiceSoap)(this)).SaveContactData(inValue);
            return retVal.Body.SaveContactDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RttClient.ClientService.SaveContactDataResponse> RttClient.ClientService.DataServiceSoap.SaveContactDataAsync(RttClient.ClientService.SaveContactDataRequest request) {
            return base.Channel.SaveContactDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<RttClient.ClientService.SaveContactDataResponse> SaveContactDataAsync(string clientId, string Type, string number) {
            RttClient.ClientService.SaveContactDataRequest inValue = new RttClient.ClientService.SaveContactDataRequest();
            inValue.Body = new RttClient.ClientService.SaveContactDataRequestBody();
            inValue.Body.clientId = clientId;
            inValue.Body.Type = Type;
            inValue.Body.number = number;
            return ((RttClient.ClientService.DataServiceSoap)(this)).SaveContactDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RttClient.ClientService.GetAddressDetailsResponse RttClient.ClientService.DataServiceSoap.GetAddressDetails(RttClient.ClientService.GetAddressDetailsRequest request) {
            return base.Channel.GetAddressDetails(request);
        }
        
        public RttClient.ClientService.AddressDetails[] GetAddressDetails(string clientId) {
            RttClient.ClientService.GetAddressDetailsRequest inValue = new RttClient.ClientService.GetAddressDetailsRequest();
            inValue.Body = new RttClient.ClientService.GetAddressDetailsRequestBody();
            inValue.Body.clientId = clientId;
            RttClient.ClientService.GetAddressDetailsResponse retVal = ((RttClient.ClientService.DataServiceSoap)(this)).GetAddressDetails(inValue);
            return retVal.Body.GetAddressDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RttClient.ClientService.GetAddressDetailsResponse> RttClient.ClientService.DataServiceSoap.GetAddressDetailsAsync(RttClient.ClientService.GetAddressDetailsRequest request) {
            return base.Channel.GetAddressDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RttClient.ClientService.GetAddressDetailsResponse> GetAddressDetailsAsync(string clientId) {
            RttClient.ClientService.GetAddressDetailsRequest inValue = new RttClient.ClientService.GetAddressDetailsRequest();
            inValue.Body = new RttClient.ClientService.GetAddressDetailsRequestBody();
            inValue.Body.clientId = clientId;
            return ((RttClient.ClientService.DataServiceSoap)(this)).GetAddressDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RttClient.ClientService.GetContactDetailsResponse RttClient.ClientService.DataServiceSoap.GetContactDetails(RttClient.ClientService.GetContactDetailsRequest request) {
            return base.Channel.GetContactDetails(request);
        }
        
        public RttClient.ClientService.ContactDetails[] GetContactDetails(string clientId) {
            RttClient.ClientService.GetContactDetailsRequest inValue = new RttClient.ClientService.GetContactDetailsRequest();
            inValue.Body = new RttClient.ClientService.GetContactDetailsRequestBody();
            inValue.Body.clientId = clientId;
            RttClient.ClientService.GetContactDetailsResponse retVal = ((RttClient.ClientService.DataServiceSoap)(this)).GetContactDetails(inValue);
            return retVal.Body.GetContactDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RttClient.ClientService.GetContactDetailsResponse> RttClient.ClientService.DataServiceSoap.GetContactDetailsAsync(RttClient.ClientService.GetContactDetailsRequest request) {
            return base.Channel.GetContactDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RttClient.ClientService.GetContactDetailsResponse> GetContactDetailsAsync(string clientId) {
            RttClient.ClientService.GetContactDetailsRequest inValue = new RttClient.ClientService.GetContactDetailsRequest();
            inValue.Body = new RttClient.ClientService.GetContactDetailsRequestBody();
            inValue.Body.clientId = clientId;
            return ((RttClient.ClientService.DataServiceSoap)(this)).GetContactDetailsAsync(inValue);
        }
    }
}
